server:
  port: 8091

spring:
  application:
    name: msvc-users
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_MSVC_USER_URL}
    username: ${DB_MSVC_USER_USERNAME}
    password: ${DB_MSVC_USER_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  jwt:
    key: ${JWT_KEY}
    issuer: ${JWT_ISSUER}

users:
  admin:
    firstName: ${ADMIN_FIRSTNAME}
    lastName: ${ADMIN_LASTNAME}
    identityNumber: ${ADMIN_IDENTITY_NUMBER}
    phoneNumber: ${ADMIN_PHONE_NUMBER}
    birthDate: ${ADMIN_BIRTH_DATE}
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}

